    window.onerror = function(message, source, lineno, colno, error) {&#xD;&#xA;    	console.log('onerror handler logging error', message);&#xD;&#xA;    	return true;&#xD;&#xA;    }&#xD;&#xA;    &#xD;&#xA;    function rejectPromise() {&#xD;&#xA;    	return Promise.reject(new Error('rejected promise'));&#xD;&#xA;    }&#xD;&#xA;    &#xD;&#xA;    async function throwAsync() {&#xD;&#xA;    	throw new Error('async exception');&#xD;&#xA;    }&#xD;&#xA;    &#xD;&#xA;    function fail() {&#xD;&#xA;    	throw new Error('exception');&#xD;&#xA;    }&#xD;&#xA;    &#xD;&#xA;    rejectPromise().then(() => console.log('success'));&#xD;&#xA;    throwAsync();&#xD;&#xA;    fail();